### ISSUE TITLE
svg滤镜实现Gooey（粘黏）效果

### ISSUE THREAD

**Issue by sollrei** [GcFETeam/10min-quick-share#11]
![circle mov](https://user-images.githubusercontent.com/1720881/58086638-9b0a7780-7bf1-11e9-99c0-3e65f7bad8bd.gif)

```css
  * { box-sizing: border-box; }
	.box {
      position: relative;
      filter: url('#colorMatrix');  /* 关键代码就这一行 */
      height: 200px;
      width: 200px;
    }

    span {
      position: absolute;
      right: 10px;
      bottom: 10px;
      height: 50px;
      width: 50px;
      border-radius: 50%;
      text-align: center;
      color: #fff;
      line-height: 50px;
      background: yellowgreen;
      transition: transform .6s cubic-bezier(0.2,0,0.15,1);
    }

    .span1 { transition-delay: .1s; }

    .span2 { transition-delay: .25s; }

    .span3 { transition-delay: .4s; }

    label {
      position: absolute;
      z-index: 10;
      right: 10px;
      bottom: 10px;
    }

    label span {
      right: 0;
      bottom: 0;
    }

    input:checked ~ .span1 {
      transform: translate3d(-80px, 0, 0);
    }

    input:checked ~ .span2 {
      transform: translate3d(-64px, -64px, 0);
    }

    input:checked ~ .span3 {
      transform: translate3d(0, -80px, 0);
    }

```

```html
	<div class="box">
    <label for="input"><span><i class="fa fa-plus"></i></span></label>
    <input type="checkbox" id="input" style="opacity: 0">
    <span class="span1"><i class="fab fa-500px"></i></span>
    <span class="span2"><i class="fab fa-facebook"></i></span>
    <span class="span3"><i class="fab fa-twitter"></i></span>
  </div>
  <svg viewBox="0 0 200 200" width="200px"  xmlns="http://www.w3.org/2000/svg" version="1.1">
    <defs>
      <filter id="colorMatrix">
      <feGaussianBlur
        in="SourceGraphic"
        stdDeviation="7"
        result="blur"
      ></feGaussianBlur>
      <feColorMatrix
        in="blur"
        type="matrix"
        values="1 0 0 0 0  
                0 1 0 0 0  
                0 0 1 0 0  
                0 0 0 18 -7"
        result="matrix"
      >
      </feColorMatrix> 
      <feBlend in="SourceGraphic" in2="matrix"></feBlend>
    </filter>
    </defs>
  </svg>

```

feGaussianBlur高斯模糊滤镜
feColorMatrix是一个颜色矩阵计算，这儿相当于(A按0-1的值算)

```
1 0 0 0 0 // R = 1*R + 0*G + 0*B + 0*A + 0
0 1 0 0 0 // G = 0*R + 1*G + 0*B + 0*A + 0
0 0 1 0 0 // B = 0*R + 0*G + 1*B + 0*A + 0
0 0 0 18 -7 // A = 0*R + 0*G + 0*B + 18*A + (-7)
```

即RGB的值不变，修改了透明度通道的对比度

使用css也可以通过添加高斯模糊和提高对比度做类似的效果，但是相比还是svg效果更好一些

css的实现可以看这个 [Shape Blobbing in CSS | CSS-Tricks](https://css-tricks.com/shape-blobbing-css/)
