### ISSUE TITLE
CSS position sticky

### ISSUE THREAD

**Issue by sollrei** [GcFETeam/10min-quick-share#16]
[position sticky](https://developer.mozilla.org/zh-CN/docs/Web/CSS/position)可以用来很方便的实现滚动粘滞效果，不需要判断滚动判断scrollTop一个属性搞定😂

```css
.box { 
  position: sticky; 
  top: 10px;  // 需要指定top right bottom left中的一个才会生效
}
```

效果相当于相对定位和固定定位的混合，在box到达顶部与*父元素*距离10像素之前为相对定位，之后就是固定定位。

推荐阅读 
[杀了个回马枪，还是说说position:sticky吧 «  张鑫旭-鑫空间-鑫生活](https://www.zhangxinxu.com/wordpress/2018/12/css-position-sticky/)

虽然兼容性

![屏幕快照 2019-06-06 上午8 39 09](https://user-images.githubusercontent.com/1720881/58999523-beabff80-8838-11e9-820e-2a7b8669e18d.png)

可以在支持的浏览器下使用，对其他做降级处理，其他常见的处理方式可以看这个 

[【前端词典】5 种滚动吸顶实现方式的比较性能升级版 - 掘金](https://juejin.im/post/5caa0c2d51882543fa41e478)
