### ISSUE TITLE
css ::marker

### ISSUE THREAD

**Issue by sollrei** [GcFETeam/10min-quick-share#22]
`::marker`伪元素用来设置列表前的符号样式，任何`display: list-item`的元素都可以使用，比如`<li>`，`<summary>` 

demo:
```css
li::marker {
  margin-right: 4px;
  color: red;
  font-size: 0.9em;
}
```
![image](https://user-images.githubusercontent.com/1720881/61094257-fda92280-a480-11e9-8307-ea211bb6c29e.png)

> 平时设计总喜欢把这个符号设置成不一样的样式，用marker就很方便，但是目前只有新版的Firfox支持(68)
