### ISSUE TITLE
css background-filter

### ISSUE THREAD

**Issue by sollrei** [GcFETeam/10min-quick-share#24]
可以为元素后面区域添加filter效果，简单例子

```css
@supports (-webkit-backdrop-filter: none) or (backdrop-filter: none) {
  .modal {
    -webkit-backdrop-filter: blur(10px);
    backdrop-filter: blur(10px);
    background-color: rgba(255, 255, 255, 0.5);  
  }
  .warning {
    display: none;
  }
}
```
![屏幕快照 2019-08-06 上午8 48 32](https://user-images.githubusercontent.com/1720881/62503681-d6e3cf00-b827-11e9-9b78-c8f19a403241.png)

支持的浏览器就可以看到白色区域部分有模糊的效果；
另外为了能生效，元素或它的背景需要有部分透明

```css
.modal { background-color: rgba(255, 255, 255, 0.95); }
```

目前支持的浏览器不是很多，可以更新下chrome感受感受

参考：
[backdrop-filter - CSS（层叠样式表） | MDN](https://developer.mozilla.org/zh-CN/docs/Web/CSS/backdrop-filter)
[The backdrop-filter CSS property | CSS-Tricks](https://css-tricks.com/the-backdrop-filter-css-property/)
