### ISSUE TITLE
多行文本溢出显示省略号

### ISSUE THREAD

**Issue by sollrei** [GcFETeam/10min-quick-share#25]
![屏幕快照 2019-11-05 上午11 44 03](https://user-images.githubusercontent.com/1720881/68176989-db07c000-ffc1-11e9-8a43-74f583a8ab67.png)

```css
.box {
  width: 200px;
  margin: 0 auto;
}
.multiple {
  overflow: hidden;
  display: -webkit-box;
  -webkit-box-orient: vertical;
  -webkit-line-clamp: 3;
}
```

```html
<div class="box">
  <p class="multiple">层叠样式表(CSS)是一种用来表现HTML(标准通用标记语言的一个应用)或XML(标准通用标记语言的一个子集)等文件样式的计算机语言。CSS不仅可以静态地修饰网页，还可以配合各种脚本语言动态地对网页各元素进行格式化。</p>
</div>
```

`-webkit-line-clamp`属性可以限制块容器内容的行数，它仅在设置`display`为`-webkit-box`或者`-webkit-line-box`并且`-webkit-box-orient`属性值为`vertical`时候才会生效

大部分情况下还需要设置`overflow: hidden`，否则多余的行数不会被截取掉，但是依然会在限制的行末尾显示省略号

参考：
[-webkit-line-clamp - CSS（层叠样式表） | MDN](https://developer.mozilla.org/zh-CN/docs/Web/CSS/-webkit-line-clamp)
