### ISSUE TITLE
css conic-gradient 绘制饼状图

### ISSUE THREAD

**Issue by sollrei** [GcFETeam/10min-quick-share#26]
```html
<div class="pie-chart"></div>
```

```css
.pie-chart {
  border-radius: 100%;
  width: 300px;
  height: 300px;
  background-image: conic-gradient(#f66 0 25%, #66f 25% 30%, #f90 30% 55%, #09f 55% 70%, #3c9 70% 100%);
}
```
![pie-chart](https://user-images.githubusercontent.com/1720881/68352880-cacb1e80-0142-11ea-93ad-21b44a226781.png)

超简单有木有真的超简单有木有除了[兼容性](https://caniuse.com/#search=conic-gradient)不好真的超简单有木有

conic-gradient和radial-gradient：

![image](https://user-images.githubusercontent.com/1720881/68352984-1b427c00-0143-11ea-93ad-37df310d3c99.png)

https://developer.mozilla.org/zh-CN/docs/Web/CSS/conic-gradient
