### ISSUE TITLE
css object-fit

### ISSUE THREAD

**Issue by sollrei** [GcFETeam/10min-quick-share#31]
用于指定可替换元素（如img iframe等）适应到其宽高的方式，可取值`fill | contain | cover | none | scale-down`

```css
img {
  height: 100px;
  width: 160px;
  object-fit: contain;
}
```

> 效果类似于给背景图设置`background-size: contain`
> 兼容性 IE (x)
