### ISSUE TITLE
css revert

### ISSUE THREAD

**Issue by sollrei** [GcFETeam/10min-quick-share#35]
重置属性值为其继承到的或者用户代理设置的样式

> 目前基本只能在safari和firefox上看到效果

DEMO：

```css
h3 { 
  font-weight: normal;
  color: blue;
  border-bottom: 1px solid grey;
}
```

```html
<h3>This will have custom styles</h3>
<p>Just some text</p>
<h3 style="all: revert">This should be reverted to browser/user defaults</h3>
<p>Just some text</p>
```

![image](https://user-images.githubusercontent.com/1720881/79812214-d20d7e00-83aa-11ea-8df3-ab285530dcef.png)

```css
.parent {
  color: blue;
}
p {
  color: red;
}
.alt {
  color: revert;
}
```

```html
<div class="parent">
  <p>Lorem, ipsum dolor.</p>
  <p class="alt">Fugit, id vel.</p>
</div>
```
![image](https://user-images.githubusercontent.com/1720881/79812165-ae4a3800-83aa-11ea-9757-3320d70ea6b2.png)

参考：
https://developer.mozilla.org/zh-CN/docs/Web/CSS/revert
