### ISSUE TITLE
CSS 加载动画

### ISSUE THREAD

**Issue by sollrei** [GcFETeam/10min-quick-share#5]
![1 mov](https://user-images.githubusercontent.com/1720881/57425514-fb8ed180-724d-11e9-8984-2d8b055d8a3d.gif)

```html
<div class="circle"></div>
```

```css
.circle {
  position: relative;
  height: 100px;
  width: 100px;
  animation: circle .7s linear infinite;
  border-radius: 50%;

  /* 右半边圈儿 */
  background-image: 
    linear-gradient(to right, #fff, #fff 49%, transparent 50%, transparent 100%), 
    linear-gradient(to top, #fa8807, transparent);
}

/* 左半边圈儿 */
.circle::after {
  content: '';
  height: 100px;
  width: 50px;
  left: 0;
  top: 0;
  position: absolute;
  border-radius: 50px 0 0 50px;
  background: linear-gradient(to top, #fa8807, red);
}

/* 中间的白色 */
.circle::before {
  content: '';
  height: 90px;
  width: 90px;
  position: absolute;
  left: 5px;
  top: 5px;
  border-radius: 50%;
  background: #fff;
  z-index: 1;
}

/* 旋转动画 */
@keyframes circle {
  0% {
    transform: rotate(0);
  }

  100% {
    transform: rotate(360deg);
  }
}
```
