### ISSUE TITLE
CSS Grid实现响应式布局

### ISSUE THREAD

**Issue by sollrei** [GcFETeam/10min-quick-share#6]
原文：[Create a responsive grid layout with no media queries, using CSS Grid - Andy Bell](https://andy-bell.design/wrote/create-a-responsive-grid-layout-with-no-media-queries-using-css-grid/?utm_source=Responsive+Design+Weekly&utm_campaign=53063bb5c4-RWD_Newsletter_359&utm_medium=email&utm_term=0_df65b6d7c8-53063bb5c4-59181357&mc_cid=53063bb5c4&mc_eid=307947acec)

html：

```
ul.auto-grid>li*12{Item $}
```

style：

`grid-template-columns`定义网格列，auto-fill表示自动填充，单元格等宽并且宽度最小16rem，max值使用1fr会把剩余空间平分给每个item，它们会拉伸占满空间

```css
/* grid */
.auto-grid {
  --auto-grid-min-size: 16rem;
  display: grid;
  /* 网格列 */
  grid-template-columns: repeat(auto-fill, minmax(var(--auto-grid-min-size), 1fr));
  /* 网格间隔 */
  grid-gap: 1rem;
}

/* ... 省略其他的一些样式 */
```
