### ISSUE TITLE
几个用在表单元素上的css4伪类

### ISSUE THREAD

**Issue by sollrei** [GcFETeam/10min-quick-share#7]
> 完整的css选择器列表： [CSS4-Selectors | All selectors from level 4 to 1](https://css4-selectors.com/selectors/)
> 需要用的还是先留意下浏览器兼容性😂

`:required`和`:optional`

```css
:required { color: red; } /* 带有required属性 */
:optional { color: blue; } /* 不带的 */
```

```html
<input required type="text">  红色文字
<input type="text">  蓝色文字
```

`:valid`和`:invalid`

```css
:invalid { color: red; } /* 非法值 */
:valid { color: blue; } /* 合法值 */
```

```html
<input required type="email">  
填写邮箱蓝色，格式错误红色
```

`:in-range`和`:out-of-range`

```css
:out-of-range { color: red; } /* 指定区间外的值 */
:in-range { color: blue; } /* 指定区间内的值 */
```

```html
<input type="number" value="2" max="4" min="0" step="1" />
0-4以外的值是红色，0-4蓝色
```

`:placeholder-shown`

```css
:placeholder-shown { border: 1px solid red; }
```

```html
<input placeholder="请输入" type="text">
没有输入内容时（placeholder显示）是红色边框
```

`:indeterminate`

```css
:indeterminate { opacity: 0.6; } 
/* checkbox 三种状态（checked, unchecked, indeterminate）中的 indeterminate（不确定） */
/* 也可用于radio 和 <progress> */
```

```html
<label for="test">Label</label>
<input type="checkbox" id="test" />

<script>
// html中没 indeterminate="true" 这个属性，所以需要js设置
  document.getElementById("test").indeterminate = true;
</script>

```
