### ISSUE TITLE
一个CSS Shapes动画

### ISSUE THREAD

**Issue by sollrei** [GcFETeam/10min-quick-share#8]
先放codepen地址[Wrecking Ball](https://codepen.io/undeadinstitute/pen/NmxpJm)

`shape-outside`属性可以定义相邻内连元素围绕的形状。

以前做图文混排时图片浮动文字环绕在图周围，环绕的边界是矩形，利用这个属性可以定义圆形`circle`，椭圆`ellipse`，图片（环绕图片中的不透明部分），或者是其他几何形状`polygon`，然后可以实现类似杂志中的炫酷排版，比如[Art Direction For The Web Using CSS Shapes — Smashing Magazine](https://www.smashingmagazine.com/2019/04/art-direction-for-the-web-using-css-shapes/)

然后拐回去说那个动画：

```css
@keyframes wreckit {
  0% {
    margin-left: -1000px;
    shape-outside: circle( 150px at -850px 150px);
  }
  100% {
    margin-left: 1000px;
    shape-outside: circle( 150px at 1150px 150px);
  }
}
```

这里使用了一个圆形，然后在左右移动中改变了圆的中心点坐标（半径 at 圆形x 圆心y），因为元素的margin-left值在改变，图形计算又是默认依据margin-box，如果不改圆心结果应该是这个样：

![屏幕快照 2019-05-14 下午4 04 43](https://user-images.githubusercontent.com/1720881/57682625-d7bff700-7664-11e9-8216-af99c4f44f33.png)

不过也可以改用其他盒模型，比如`shape-outside: circle(100px) content-box;`：

![屏幕快照 2019-05-14 下午4 04 05](https://user-images.githubusercontent.com/1720881/57682637-db537e00-7664-11e9-97d0-f9ace1fe0962.png)

> 话说为啥要分享这个动画……因为第一眼看到的时候觉得迷之搞笑😂

参考
标准：
[shape-outside - CSS（层叠样式表） | MDN](https://developer.mozilla.org/zh-CN/docs/Web/CSS/shape-outside)
文章：
[Take A New Look At CSS Shapes — Smashing Magazine](https://www.smashingmagazine.com/2018/09/css-shapes/)
[It’s a trap-ezoid: CSS Shapes aren’t what you’dexpect](https://blog.logrocket.com/its-a-trap-ezoid-css-shapes-aren-t-what-you-d-expect-fe27a210001e)
